default["postgres"]["version"] = "9.3"
default["postgres"]["conf_path"] = "/home/vagrant/postgres/postgresql.conf"
default["postgres"]["username"] = "koality"
default["postgres"]["password"] = "lt3"
default["postgres"]["database_name"] = "koality"